plugins:
  - prettier-plugin-svelte
  - '@trivago/prettier-plugin-sort-imports'

arrowParens: avoid
importOrder:
  - '^$lib/(.*)$'
  - '^[./]'
printWidth: 100
semi: false
singleQuote: true
svelteIndentScriptAndStyle: true
svelteSortOrder: options-scripts-markup-styles
svelteStrictMode: false
tabWidth: 2
trailingComma: all

overrides:
  - files:
      - '*.js'
      - '*.cjs'
    options:
      parser: meriyah
  - files:
      - '*.mdx'
      - '*.svx'
    options:
      parser: markdown
